pipeline {
    environment {
        GITHUB_CREDENTIALS = 'dfcb3cb6-d9f8-474e-8a68-f17d371665c9'
        GITHUB_URL = 'https://github.com/elfergouchmohamed/SpringBoot_Code.git'
        GITHUB_BRANCH = 'master'
    }

    agent any

    tools {
        maven 'MAVEN'
    }

    stages {
        stage('Clone the code source') {
            agent {
                label 'Jenkins-Agent'
            }
            steps {
                script {
                    git url: "${GITHUB_URL}", branch: "${GITHUB_BRANCH}", credentialsId: "${GITHUB_CREDENTIALS}", dir: 'Cinema_Code'
                }
            }      
        }
        stage('Build') {
            steps {
                dir('Cinema_Code'){
                    sh 'mvn clean install -DskipTests'
                }
            }
        }
    }
}
