    pipeline {
        environment {
            GITHUB_CREDENTIALS = 'dfcb3cb6-d9f8-474e-8a68-f17d371665c9'
            GITHUB_URL = 'https://github.com/elfergouchmohamed/SpringBoot_Code.git'  
            GITHUB_BRANCH = 'master'
            JAVA_HOME = '/usr/lib/jvm/java-11-openjdk-amd64'
            M2_HOME = '/opt/maven'
            MAVEN_HOME = '/opt/maven'
            PATH = "${M2_HOME}/bin:${JAVA_HOME}/bin:${PATH}"
        } 
        agent any
        
        stages {
            /*
            stage('Start the Jenkins Agent') {
                agent { 
                    label 'Jenkins-Master' 
                }
                steps {
                    script {
                        sh 'az vm start -g jenkins-rg -n jenkins-vm'
                    }
                    echo 'Wait 60 seconds for the Jenkins Agent to start'
                    sleep(time: 60, unit: 'SECONDS')
                }
            }
            */
            stage('Clone the code source') {
                agent {
                    label 'Jenkins-Agent'
                }
                steps {
                    script {
                        git url: "${GITHUB_URL}", branch: "${GITHUB_BRANCH}", credentialsId: "${GITHUB_CREDENTIALS}", dir: 'Cinema_Code'
                    }
                }      
            }
            
            stage('Build the code') {
                agent {
                    label 'Jenkins-Agent'
                }
                steps {
                    script {
                        sh 'mvn clean install -DskipTests'
                    }
                }
            }
            /*
            stage('Stop the Jenkins Agent') {
                agent {
                    label 'Jenkins-Master'
                }
                steps {
                    script {
                        sh 'az vm stop -g jenkins-rg -n jenkins-vm'
                    }
                }
            }
            */
        }        
    }
