pipeline {
    stages {
        agent { label 'Jenkins-Master' }
        stage('Start the Jenkins Agent') {
            steps {
                script {
                 sh 'az vm start -g jenkins-rg -n jenkins-vm'
                }
            }
        }
    }
}
